name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Changelog
        id: changelog
        run: |
          echo "## Changelog" > changelog.md
          echo "" >> changelog.md
          git log -1 --pretty=format:"%h - %s (%an)" >> changelog.md
          echo "" >> changelog.md
          cat changelog.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body_path: ./changelog.md
          draft: false
          prerelease: false
